In [1]:
import utils
import torch
from pprint import pprint
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import mplhep as hep
from coffea.util import load
import numpy as np
import pandas as pd
import awkward as ak
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
from numba import njit
import vector
import numba as nb
import numpy.ma as ma
from torch.utils.data import DataLoader

vector.register_numba()
vector.register_awkward()


hep.style.use(hep.style.ROOT)

from Dataset_Parton_Level import Dataset_PartonLevel
from Dataset_Reco_Level import Dataset_RecoLevel
from utils import Test

In [2]:
data_for_dataloader_Parton = Dataset_PartonLevel("../../../dataset_1/only_v6/")
batch_size = 64

data_loaded_Parton = DataLoader(data_for_dataloader_Parton, batch_size=batch_size, shuffle=False, drop_last=True)
 
mask_partons, data_partons, mask_lepton_partons, data_lepton_partons, mask_boost, data_boost, data_intermediate, data_intermediate_cartesian = next(iter(data_loaded_Parton))

In [25]:
test = Test()

px_reco, py_reco = test.check_px_py((data_partons, data_lepton_partons))
pz_reco = test.check_pz((data_partons, data_lepton_partons))

print(px_reco)


tensor([  0.2143,  -1.1946,   5.4254,  -8.9627,  -2.1405,  -1.1648,  -0.2309,
         -7.7747,  -0.3425,   8.9211,  -3.0507,  10.4014,  -1.4666,  -9.4703,
         -2.2471,  -0.6820,   1.1333,  -0.2550,  -5.4682,  -0.9206,  18.3314,
         -2.7474,  -5.2308,   8.5098,   1.0489,  11.8814,   3.1727,  -1.3099,
          0.9343,   4.9917,  -0.9395,  -8.5719,  -4.9361,  -5.3369,  -1.1443,
          8.2595,   5.3711,  -3.6933,  11.9946,   5.0625,  14.9844,  -2.7412,
         -1.2384,  -1.9179,   0.9550,   0.5223,  -2.5363,  -3.4263,   6.0242,
          0.3880,   2.1137,  -0.5204,   3.9816, -15.1647,   3.3089, -16.2008,
        -17.4006, -16.2257,  -6.4890,  -2.5146,   4.5341,  12.6313,  -5.9611,
          1.3300], dtype=torch.float32)


In [27]:
higgs = data_for_dataloader_Parton.get_Higgs()

print(higgs["px"])

ValueError: key "px" does not exist (not in record)

(https://github.com/scikit-hep/awkward-1.0/blob/1.10.3/src/libawkward/util.cpp#L525)

In [19]:
print(data_intermediate.shape)
px_reco, py_reco = test.check_px_py((data_intermediate,))
pz_reco = test.check_pz((data_intermediate,))

print(px_reco)

torch.Size([64, 3, 4])
tensor([ -28.0865,   12.6975,  -24.4900, -351.6441,    2.2500,  -37.9033,
          -5.2884,  -30.3021,    0.7989,   60.3360,    5.3218, -203.1643,
           7.0983,   41.1508,  -60.2815,  -17.0660,  -15.7414,  -48.2039,
          31.2225,    4.0679,   26.2130,  -24.8902,    0.6917,  -38.1038,
           7.3298,  -11.1296,   10.1669, -127.5644,   -0.4506,   65.6573,
         -37.0534,  -10.4256,   42.9284,   11.7187,    5.1596,  -47.6983,
          32.1057,   21.1514,  129.7833,   62.1552,  -70.4443,  -13.6559,
        -213.2667, -110.6834,   -9.9286,   -1.0453,   17.3709,  -66.9061,
          34.4568,   14.5547,   38.9792,    2.6593,  107.7902,  -50.4500,
          -2.1179,   71.8173,   39.0152,  -85.9293,   56.4218,  -36.0594,
          49.6203,   16.0213,  -28.2780,  -12.2764], dtype=torch.float32)


In [20]:
data_for_dataloader_Reco = Dataset_RecoLevel("../../../dataset_1/only_v6/")
batch_size = 64

data_loaded_Reco = DataLoader(data_for_dataloader_Reco, batch_size=batch_size, shuffle=False, drop_last=True)
 
mask_lepton, data_lepton, mask_jets, data_jets, mask_met, data_met, mask_boost, data_boost = next(iter(data_loaded_Reco))

jets file already exists
lepton_reco file already exists
met file already exists
boost file already exists


In [21]:
test = Test()

px_reco, py_reco = test.check_px_py((data_lepton, data_jets, data_met))
pz_reco = test.check_pz((data_jets, data_lepton, data_met))

print(px_reco)

tensor([ 3.8147e-06, -4.7684e-06,  9.5367e-07,  0.0000e+00,  7.6294e-06,
         1.3351e-05,  0.0000e+00,  0.0000e+00,  2.2888e-05, -1.1444e-05,
        -2.2888e-05, -7.6294e-06,  1.9073e-06, -1.1444e-05,  0.0000e+00,
        -1.1444e-05,  1.9073e-05,  7.6294e-06,  7.6294e-06, -6.6757e-06,
        -3.8147e-06,  1.5259e-05, -2.8610e-05,  3.8147e-06,  1.9073e-06,
        -9.5367e-07, -7.6294e-06, -1.5259e-05, -1.1444e-05,  7.6294e-06,
         1.0490e-05, -3.8147e-06, -1.1444e-05,  9.5367e-07, -1.5259e-05,
        -1.9073e-05,  0.0000e+00,  1.9073e-05, -1.5259e-05, -3.0518e-05,
        -4.6492e-06,  1.1444e-05, -1.7166e-05,  3.0518e-05, -7.6294e-06,
         1.7166e-05, -2.2888e-05, -8.5831e-06,  2.2888e-05, -4.7684e-06,
         7.6294e-06,  7.6294e-06,  1.9073e-06, -1.1176e-05, -1.3828e-05,
         1.1444e-05,  2.2888e-05,  3.5763e-06,  2.4796e-05,  3.0518e-05,
        -1.9073e-06,  0.0000e+00, -3.4332e-05,  1.5259e-05],
       dtype=torch.float32)
