In [1]:
import utils
import torch
from pprint import pprint
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import mplhep as hep
import numpy as np
import pandas as pd
import awkward as ak
from numba import njit
import vector
import numba as nb
import numpy.ma as ma
from torch.utils.data import DataLoader

vector.register_numba()
vector.register_awkward()


hep.style.use(hep.style.ROOT)

from Dataset_Parton_Level import Dataset_PartonLevel
from Dataset_Reco_Level import Dataset_RecoLevel
from utils import Test

In [2]:
data_for_dataloader_Parton = Dataset_PartonLevel("../../dataset/")
batch_size = 64

data_loaded_Parton = DataLoader(data_for_dataloader_Parton, batch_size=batch_size, shuffle=False, drop_last=True)
 
(mask_partons, data_partons, 
 mask_lepton_partons, data_lepton_partons, 
 mask_boost, data_boost, 
 mask_incomining_particles_boost, data_incomining_particles_boost,
 data_intermediate, data_intermediate_cartesian) = next(iter(data_loaded_Parton))

Create new file for partons
Create new file for lepton_partons
Create new file for boost
Create new file for incoming_particles_boost
Create new file for H_t_tbar
(569993, 3, 4)
Create new file for H_t_tbar_cartesian
(569993, 3, 4)


In [7]:
data_intermediate_cartesian

tensor([[[ 1.5124e+02, -3.9729e+01, -3.4956e+01, -6.6693e+01],
         [ 1.8805e+02,  2.4804e+01,  6.9881e+01, -1.7345e+01],
         [ 1.9597e+02,  1.4931e+01, -3.4919e+01,  8.4024e+01]],

        [[ 2.0807e+02, -1.4753e+02, -3.6611e+01,  6.7551e+01],
         [ 3.4320e+02,  1.6940e+02,  2.3598e+02,  7.7807e+01],
         [ 3.0204e+02, -2.1870e+01, -1.9937e+02, -1.4536e+02]],

        [[ 1.5277e+02,  7.6586e+01,  3.1316e+01,  2.9433e+01],
         [ 2.7938e+02, -1.4260e+02, -1.6450e+02,  3.0261e+01],
         [ 2.3412e+02,  6.6027e+01,  1.3318e+02, -5.9712e+01]],

        [[ 1.6416e+02,  9.6078e+01, -2.4246e+01,  3.8788e+01],
         [ 2.8211e+02,  7.4660e+01,  4.0542e+00,  2.0840e+02],
         [ 3.4547e+02, -1.7073e+02,  2.0182e+01, -2.4719e+02]],

        [[ 1.5998e+02,  3.8636e+01, -1.2214e+01, -9.1248e+01],
         [ 2.1458e+02, -2.5473e+01,  2.8173e+01,  1.2069e+02],
         [ 1.7670e+02, -1.3162e+01, -1.5959e+01, -2.9440e+01]],

        [[ 1.6744e+02, -8.6786e+01, -3.5417e+

In [8]:
test = Test()

px_reco, py_reco = test.check_px_py((data_partons, data_lepton_partons))
pz_reco = test.check_pz((data_partons, data_lepton_partons))

print(px_reco)


tensor([  30.0220,  -15.9037,   41.1875,  727.3641,   -6.6298,   45.0416,
           8.7170,   15.0647,   -1.4929,  -45.2757,  -11.5224,  460.2345,
         -12.9950, -248.0050,   63.9294,   24.3721,   18.8089,   75.4713,
         -95.1976,   -9.3718,    9.1190,   36.6920,  -12.5068,   64.0875,
          -7.0365,   56.3485,   -3.9229,    2.3494,  -90.9467,   64.1489,
         -56.0130,  -23.0999,   -9.9374,   74.8010,  -30.8453, -126.4774,
         -14.8701,  -61.7370,  114.4925,    8.7608,  374.6742,  126.3225,
          21.8059,    2.3331,  -28.6155,   68.4909,  -25.3925,  -14.4999,
         -41.1643,   -3.7247, -119.4965,   22.4348,    8.7911, -137.2064,
         -96.1791,   98.8081,  -74.4934,   37.2399,  -45.6427,    9.1010,
          18.3803,    1.3258,   15.8623, -139.9253], dtype=torch.float32)


In [11]:
print(data_intermediate.shape)
px_reco, py_reco = test.check_px_py((data_intermediate,))
pz_reco = test.check_pz((data_intermediate,))

print(py_reco)
print(px_reco)

torch.Size([64, 3, 4])
tensor([ 0.0051, -0.0002, -0.0014, -0.0094, -0.0006, -0.0065, -0.0021,  0.0294,
        -0.0052,  0.0027,  0.0043,  0.0006,  0.0038, -0.0038,  0.0050,  0.0009,
         0.0009, -0.0025, -0.0104, -0.0001, -0.0027, -0.0032,  0.0117, -0.0056,
         0.0004,  0.0025, -0.0036,  0.0136,  0.0140,  0.0085, -0.0079, -0.0016,
        -0.0038,  0.0022, -0.0016, -0.0039,  0.0006,  0.0052, -0.0037, -0.0029,
        -0.0071,  0.0088, -0.0011, -0.0023, -0.0018,  0.0022, -0.0008, -0.0006,
        -0.0069, -0.0014, -0.0011, -0.0028,  0.0079,  0.0014, -0.0052, -0.0018,
        -0.0083,  0.0108,  0.0018,  0.0050,  0.0020, -0.0003,  0.0015,  0.0035],
       dtype=torch.float32)
tensor([ 5.6210e-03, -1.2589e-04,  1.3191e-02,  7.9041e-03,  1.1301e-03,
         2.3333e-03, -1.0223e-03,  1.3367e-02, -2.1973e-03, -4.1428e-03,
        -2.0508e-02,  1.5259e-05,  1.8463e-03, -2.1225e-02,  2.6665e-03,
         5.2872e-03,  1.8311e-04,  1.3855e-02,  3.0518e-05, -7.4768e-04,
         4.4708e

In [20]:
data_for_dataloader_Reco = Dataset_RecoLevel("../../../dataset_1/only_v6/")
batch_size = 64

data_loaded_Reco = DataLoader(data_for_dataloader_Reco, batch_size=batch_size, shuffle=False, drop_last=True)
 
mask_lepton, data_lepton, mask_jets, data_jets, mask_met, data_met, mask_boost, data_boost = next(iter(data_loaded_Reco))

jets file already exists
lepton_reco file already exists
met file already exists
boost file already exists


In [21]:
test = Test()

px_reco, py_reco = test.check_px_py((data_lepton, data_jets, data_met))
pz_reco = test.check_pz((data_jets, data_lepton, data_met))

print(px_reco)

tensor([ 3.8147e-06, -4.7684e-06,  9.5367e-07,  0.0000e+00,  7.6294e-06,
         1.3351e-05,  0.0000e+00,  0.0000e+00,  2.2888e-05, -1.1444e-05,
        -2.2888e-05, -7.6294e-06,  1.9073e-06, -1.1444e-05,  0.0000e+00,
        -1.1444e-05,  1.9073e-05,  7.6294e-06,  7.6294e-06, -6.6757e-06,
        -3.8147e-06,  1.5259e-05, -2.8610e-05,  3.8147e-06,  1.9073e-06,
        -9.5367e-07, -7.6294e-06, -1.5259e-05, -1.1444e-05,  7.6294e-06,
         1.0490e-05, -3.8147e-06, -1.1444e-05,  9.5367e-07, -1.5259e-05,
        -1.9073e-05,  0.0000e+00,  1.9073e-05, -1.5259e-05, -3.0518e-05,
        -4.6492e-06,  1.1444e-05, -1.7166e-05,  3.0518e-05, -7.6294e-06,
         1.7166e-05, -2.2888e-05, -8.5831e-06,  2.2888e-05, -4.7684e-06,
         7.6294e-06,  7.6294e-06,  1.9073e-06, -1.1176e-05, -1.3828e-05,
         1.1444e-05,  2.2888e-05,  3.5763e-06,  2.4796e-05,  3.0518e-05,
        -1.9073e-06,  0.0000e+00, -3.4332e-05,  1.5259e-05],
       dtype=torch.float32)


In [12]:
import torch
from memflow.phasespace.phasespace import PhaseSpace
import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np
from  memflow.phasespace.utils import *
torch.set_default_dtype(torch.double)

2023-03-23 10:24:52.396527: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-23 10:24:53.975303: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/opt/LHAPDF/lib:/opt/MG5_aMC_v3_4_1/lib:/.singularity.d/libs
2023-03-23 10:24:53.975705: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/opt/LHAPDF/lib:/opt/MG5_aMC_v3_4_1/lib:/.singularity.d/libs
2023-0

In [13]:
E_CM = 13000
phasespace = PhaseSpace(E_CM, [21,21], [25,6,-6])

2023-03-23 10:24:58.046711: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/opt/LHAPDF/lib:/opt/MG5_aMC_v3_4_1/lib:/.singularity.d/libs
2023-03-23 10:24:58.046981: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)


In [15]:
help(phasespace.get_ps_from_momenta)

Help on method get_ps_from_momenta in module memflow.phasespace.phasespace:

get_ps_from_momenta(momenta, x1, x2) method of memflow.phasespace.phasespace.PhaseSpace instance



In [17]:
data_incomining_particles_boost.squeeze()

tensor([[  998.8601,     0.0000,     0.0000,   807.2465],
        [ 2170.4863,     0.0000,     0.0000,  1982.0712],
        [ 1156.0483,     0.0000,     0.0000,  -876.8878],
        [ 1947.3667,     0.0000,     0.0000,  1258.1005],
        [  918.5474,     0.0000,     0.0000,   718.6520],
        [ 1321.9490,     0.0000,     0.0000,   969.3566],
        [ 1052.2976,     0.0000,     0.0000,   268.6100],
        [ 2264.4272,     0.0000,     0.0000,  1022.6669],
        [  838.9816,     0.0000,     0.0000,   224.0028],
        [ 1373.1394,     0.0000,     0.0000,  -933.1426],
        [ 1791.2540,     0.0000,     0.0000,  1072.6299],
        [ 2280.0483,     0.0000,     0.0000,  -755.8174],
        [  986.9861,     0.0000,     0.0000,   459.8828],
        [ 3615.0273,     0.0000,     0.0000,  2882.7905],
        [  623.2109,     0.0000,     0.0000,  -183.2638],
        [  911.8309,     0.0000,     0.0000,   213.0432],
        [  819.0708,     0.0000,     0.0000,   311.8534],
        [ 1824

In [ ]:
data_incomining_particles_boost.squeeze()

In [ ]:
r = phasespace.get_ps_from_momenta(momenta, x1, x2)  #get from partons and 